import { EstadoReporte, NivelPrioridad, NivelRiesgo, TipoProblema, type ReporteZonaOscura } from "@prisma/client";

export const reportesDemo: ReporteZonaOscura[] = [
  {
    id: "demo-1",
    codigo: "ZO-2026-0001",
    titulo: null,
    direccion: "Av. Los Álamos cuadra 5",
    referencia: null,
    distrito: "Pachacámac",
    latitud: -12.2296,
    longitud: -76.8614,
    tipoProblema: TipoProblema.LUZ_APAGADA,
    nivelRiesgo: NivelRiesgo.MEDIO,
    descripcion: "Luminaria apagada desde hace varios días en una calle con tránsito vecinal.",
    estado: EstadoReporte.PENDIENTE,
    prioridad: NivelPrioridad.MEDIA,
    ciudadanoId: "demo-ciudadano",
    funcionarioAsignadoId: null,
    fechaSolucion: null,
    fechaCreacion: new Date("2026-05-07T10:00:00-05:00"),
    fechaActualizacion: new Date("2026-05-07T10:00:00-05:00")
  },
  {
    id: "demo-2",
    codigo: "ZO-2026-0002",
    titulo: null,
    direccion: "Jr. Las Palmeras cuadra 4",
    referencia: null,
    distrito: "Manchay",
    latitud: -12.1129,
    longitud: -76.8832,
    tipoProblema: TipoProblema.SIN_POSTE_LUZ,
    nivelRiesgo: NivelRiesgo.ALTO,
    descripcion: "Tramo sin poste de luz cerca de una zona de paso peatonal.",
    estado: EstadoReporte.EN_EVALUACION,
    prioridad: NivelPrioridad.ALTA,
    ciudadanoId: "demo-ciudadano",
    funcionarioAsignadoId: "demo-municipal",
    fechaSolucion: null,
    fechaCreacion: new Date("2026-05-06T18:30:00-05:00"),
    fechaActualizacion: new Date("2026-05-06T18:30:00-05:00")
  },
  {
    id: "demo-3",
    codigo: "ZO-2026-0003",
    titulo: null,
    direccion: "Av. Principal con Calle 8",
    referencia: null,
    distrito: "José Gálvez",
    latitud: -12.2015,
    longitud: -76.9348,
    tipoProblema: TipoProblema.ZONA_COMPLETAMENTE_OSCURA,
    nivelRiesgo: NivelRiesgo.ALTO,
    descripcion: "Zona completamente oscura con alta percepción de inseguridad.",
    estado: EstadoReporte.EN_PROCESO,
    prioridad: NivelPrioridad.ALTA,
    ciudadanoId: "demo-ciudadano",
    funcionarioAsignadoId: "demo-municipal",
    fechaSolucion: null,
    fechaCreacion: new Date("2026-05-05T20:15:00-05:00"),
    fechaActualizacion: new Date("2026-05-05T20:15:00-05:00")
  }
];
