export const limaDistricts = [
  "Ancón",
  "Ate",
  "Barranco",
  "Breña",
  "Carabayllo",
  "Chaclacayo",
  "Chorrillos",
  "Cieneguilla",
  "Comas",
  "El Agustino",
  "Independencia",
  "Jesús María",
  "La Molina",
  "La Victoria",
  "Lima",
  "Lince",
  "Los Olivos",
  "Lurigancho",
  "Lurín",
  "Magdalena del Mar",
  "Miraflores",
  "Pachacámac",
  "Pucusana",
  "Pueblo Libre",
  "Puente Piedra",
  "Punta Hermosa",
  "Punta Negra",
  "Rímac",
  "San Bartolo",
  "San Borja",
  "San Isidro",
  "San Juan de Lurigancho",
  "San Juan de Miraflores",
  "San Luis",
  "San Martín de Porres",
  "San Miguel",
  "Santa Anita",
  "Santa María del Mar",
  "Santa Rosa",
  "Santiago de Surco",
  "Surquillo",
  "Villa El Salvador",
  "Villa María del Triunfo"
];

export const limaDistrictQuickPoints = [
  { label: "San Juan de Lurigancho", lat: -12.0087, lng: -77.0055 },
  { label: "La Victoria", lat: -12.0686, lng: -77.0128 },
  { label: "Comas", lat: -11.9392, lng: -77.0598 },
  { label: "Villa El Salvador", lat: -12.2135, lng: -76.9363 },
  { label: "Ate", lat: -12.0614, lng: -76.9331 },
  { label: "Pachacámac", lat: -12.2296, lng: -76.8614 }
];
